### ISSUE TITLE
rgb to multiple level color name mapping?

### ISSUE THREAD

**Issue by apiszcz** [ksmet1977/luxpy#12]
I am seeking a python multi-level rgb to colorname mapping module.

rgb2name((r,g,b), level)
level 0 might be 8 or 16 basic color names. (e.g. green)
level 1 might have 32 to 64 color names. (e.g. dark green, green, light green)
level 2 might have 64 to 256 color names. (more variants)

Is anything like this available? 

Thank you.

**Comment by ksmet1977** [comment]
No function to convert rgb values to color names, such as green, cyan, magenta ... is available. But if you have conversion lists, I'd be happy to look into this.

regards,
Kevin
