### ISSUE TITLE
Error in xyz_to_cct_search_fast

### ISSUE THREAD

**Issue by jcerpent** [ksmet1977/luxpy#13]
Dear,

I am working on an optimisation project related to spectral distributions and different constraints. One of the constraints includes the TM-30 fidelity index (spd_to_cri method), but after a while LuxPy raises an error message in the xyz_to_cct_search_fast method. I'm not sure why this is happening, or whether this is a bug of some sort. I have included a screenshot so you have an idea what exactly is the error. What could cause this?

Thanks.
![error](https://user-images.githubusercontent.com/71133104/92925173-618afa80-f43a-11ea-9f36-9da69409124d.PNG)

**Comment by ksmet1977** [comment]
Your optimization probably generated an xyzw that is too far from the valid range. In that case, some code gets called to break the search loop. I noticed that on line 674 rtols was defined as 'rtols = np.ones((4,))*1e12', but the 'cnt' resets when > 4, so please change line 674 to 'rtols = np.ones((5,))*1e12' or download the latest luxpy from github (I haven't changed the version number for this!, but github has been updated). Please let me know if the problem persists. If yes, send me a message with the xyzw value (as many decimals as possible) that creates the problem so I can have a further look.
