### ISSUE TITLE
UnboundLocalError: local variable 'dotAB' referenced before assignment in dot23()

### ISSUE THREAD

**Issue by joshuakraemer** [ksmet1977/luxpy#16]
Calling `luxpy.color.cam.zcam(numpy.array([10, 20, 30]))` results in the error `UnboundLocalError: local variable 'dotAB' referenced before assignment`. The traceback points to function "dot23()". The reason for this error seems to be that all assignments of the returned variable "dotAB" are behind if conditions.

**Comment by ksmet1977** [comment]
your input is a vector, but all colorimetric data in luxpy is always either 2D or 3D arrays with the actual colorimetric values on the last axis. 
Calling ```luxpy.color.cam.zcam(numpy.array([[10, 20, 30]]))``` works without a problem.

**Comment by joshuakraemer** [comment]
Thanks and sorry for the mistake!
