### ISSUE TITLE
ZCAM is published

### ISSUE THREAD

**Issue by joshuakraemer** [ksmet1977/luxpy#17]
Accessing the ZCAM functions prints the following warning:
```WARNING: Z-CAM is as yet unpublished and under development, so parameter values might change! (07 Oct, 2020```

But ZCAM has already been published (https://www.osapublishing.org/oe/fulltext.cfm?uri=oe-29-4-6036).

**Comment by ksmet1977** [comment]
Ok. Thanks for letting me know. I'll see if I can update zcam as soon as possible.

**Comment by ksmet1977** [comment]
I've implemented the published version of ZCAM. However, note that the example values in the supplementary material cannot be exactly replicated. I've checked all parameters, and I think they are correct, but there is already a discrepancy for the XYZ to Jz, az, bz conversion, especially for the bz value. The only reason I can see (assuming I indeed not missed any wrong parameter values, but please check yourself), is that the CAT02 chromatic adaptation transform parameters or more likely the XYZ of the D65 reference white that Safdar et al used in their calculations is different from what one would normally use/get: for XYZw of D65, maybe they used a different, non-standard wavelength range, mistyped, or something else?. In any case, (and I've reported this to the authors months ago), published values of D65 for the CIE 1932 2° observer don't lead to a (az, bz) values of (0,0) which is what one would expect for a stimulus matching the reference white. In addition (also reported to the authors), they report that for Iz the reference is a D65 stimulus of 10000 cd/m², but Iz becomes 1 only for a much higher value! So there is probably something wrong there as well. So for now, I won't put any more time in this until perhaps somebody else can very my findings or point out where I might have made a coding mistaking. 

If you want to use the new ZCAM update your luxpy copy from github directly. I'll make another release for pypi later, but I'm working on some other things that I want to incorporate in the new version.

**Comment by joshuakraemer** [comment]
That's great, thank you very much!

I've tried to test the worked examples, but it doesn't work as expected. Maybe I'm doing something wrong, but it seems the CAT is not even applied? The following function call gives the same result when I remove the parameter "xyzw".

```
>>> luxpy.color.cam.zcam(numpy.array([[185, 206, 163]]), xyzw = numpy.array([[256, 264, 202]]), outin = "J,C,h", cieobs = "1931_2", conditions = {"La": 264, "Yb": 100, "surround": "avg", "D": None, "Dtype": "cat02"}, forward = True, mcat = "cat02")
array([[127.7651,   4.7005, 104.3055]])
```

By the way, it would be good to have a<sub>z</sub> and b<sub>z</sub> as output parameters for testing.

**Comment by ksmet1977** [comment]
Maybe you can try again, I noticed that there was still a line of code in
there for testing the location of the origin that always sets the xyzw to
that of D65.
In any case, as I mentioned I can't match the values as in the examples,
while the parameters are the same

Op vr 30 apr. 2021 om 17:04 schreef Joshua Krämer ***@***.***

**Comment by ksmet1977** [comment]
btw to get the Iz,az,bz out, you could try setting out = 'iabz' as that is
the name of the variable storing these values in the calculation. That's
how I tested the correctness of these valuesn but already here there are
differences, which I think are likely due to the way the corresponding
colors are calculated with the CAT02 matrix. When at some point I got the
matlab code from one of the authors, I noticed that some of the parameters
were different than in the paper and his code for the forward model applied
chromatic adaptation while in inverse did not (or vice versa, can't quite
remember). You're welcome to further try and figure his out using the code
in the zcam.py file and let me know once you might have figured out where
the exact problem is, but I think it might be difficult without more
intermediate steps in the worked examples in the supplementary file to the
paper.


Op vr 30 apr. 2021 om 17:15 schreef kevin smet ***@***.***>:

**Comment by joshuakraemer** [comment]
Thank you, it works now. I think a clarification from the authors is necessary. I will try to contact them and ask for a current Matlab implementation.

**Comment by joshuakraemer** [comment]
I think I have found a small bug with the ZCAM implementation: Hue quadrature _H_ seems to be interpreted as hue angle _h_ in backwards mode.

```
>>> luxpy.color.cam.zcam(luxpy.color.cam.zcam(numpy.array([[50, 10, 100]]), outin = "J,C,H", forward = False), outin = "J,C,H", forward = True)
array([[[ 50. ,  10. , 135.5]]])
>>> luxpy.color.cam.zcam(luxpy.color.cam.zcam(numpy.array([[50, 10, 100]]), outin = "J,C,H", forward = False), outin = "J,C,h", forward = True)
array([[[ 50.,  10., 100.]]])
```

**Comment by ksmet1977** [comment]
Thanks for letting me know
Fixed that, it was never supposed to work with H quadrature, but now it
should. (I've also changed CIECAM02, CIECAM16 and CAM18sl to now be able to
work with inverse of hue_quadrature)
I've also just released a new version of luxpy on pypi and conda.

regards,
Kevin

Op di 4 mei 2021 om 10:10 schreef Joshua Krämer ***@***.***>:

**Comment by joshuakraemer** [comment]
Thanks a lot!
