### ISSUE TITLE
Feature request: sRGB gamma function

### ISSUE THREAD

**Issue by joshuakraemer** [ksmet1977/luxpy#18]
Currently, a gamma value of 2.4 is used for sRGB conversions. It would be nice if the sRGB gamma function could be used instead.

**Comment by ksmet1977** [comment]
Not sure what you mean. sRGB is defined with a gamma = 2.4 (at least for reasonably light stimuli; dark stimuli use a linear function). See: https://www.image-engineering.de/library/technotes/958-how-to-convert-between-srgb-and-ciexyz
In addition, if you want another gamma, you can change the 2.4 value to whatever you like using the 'gamma' keyword argument.

**Comment by joshuakraemer** [comment]
The sRGB gamma function is meant to approximate a power curve with a gamma of 2.2 (see https://www.w3.org/Graphics/Color/sRGB.html). This is achieved by a linear part near zero and a power curve with an exponent of 2.4 and an offset elsewhere. I have checked your code and it already implements this sRGB gamma function correctly. However, from the documentation and the "gamma" parameter, I did expect a usual gamma function with the given gamma value instead of the sRGB gamma function. But the "gamma" parameter does not represent a gamma value, it just changes the exponent of the sRGB gamma function. Thus, to get the sRGB gamma function with an approximate gamma value of 2.2, a "gamma" parameter of 2.4 has to be provided, which I think is misleading. In my opinion, it also doesn't make sense to change the exponent of the sRGB function while keeping the offset (any value except 2.4 results in a curve that neither follows the given gamma value nor approximates the intended gamma value of 2.2). In my opinion, a "gamma" parameter would only make sense if it would define the overall gamma.

**Comment by ksmet1977** [comment]
That's what I needed at the time when coding it, but I've just made the
functions more general.
You can now use a pure gamma function (set use_linear_part to False and
offset to zero), or you can choose different offsets. You can even use a
different conversion matrix. It's up to the user to make sure the linear
and nonlinear parts stitch well together when using non-default offsets and
gamma values when setting use_linear_part to true.


Op vr 30 apr. 2021 om 13:19 schreef Joshua Krämer ***@***.***
