### ISSUE TITLE
reference to xyz_to_duv missing in cct.py

### ISSUE THREAD

**Issue by tky-mti** [ksmet1977/luxpy#2]
Noticed that after recent commit, `xyz_to_duv` is missing from `__all__` in `cct.py`. Other references may be missing, too?

_____
Great package! Thanks for putting this together and maintaining it!

**Comment by ksmet1977** [comment]
Thanks for letting me know.
I've been and still am rearranging some of the structure of the package,
and will probably add in some classes (SPD, CDATA, XYZ, LAB) with dedicated
methods.
I still need to start testing everything though.
In the next distribution, I'll correct it (and probably some other errors
that snuck in).

regards,
Kevin

2018-04-09 16:16 GMT+02:00 tky-mti <notifications@github.com>:
