### ISSUE TITLE
Converting RGB to spectrum and back to RGB

### ISSUE THREAD

**Issue by Tenceto** [ksmet1977/luxpy#23]
I have an RGB image and I want to simulate the effects of a chromatic filter over it. Namely, I wrote a function that converts RGB to spectral data, performs the filtering, and then comes back to RGB. The problem is that even when I skip the filtering step, the input and output images are extremely different. I don't know if this is an expected behaviour, if I'm doing something wrong or if there's a bug in the library.

Here's a toy example to show what I mean:

```
import numpy as np
import luxpy as lx
import matplotlib.pyplot as plt
import cv2

def filter_img(rgb_img, lambda_min, lambda_max):
    # Store the actual shape of the image
    original_shape = rgb_img.shape

    # Calculate the spectrum for each pixel in the image
    spectral_data = lx.toolboxes.rgb2spec.convert(rgb_img.reshape(-1, 3), intent="spd")
    lambdas, spectra = spectral_data[0], spectral_data[1:]

    # Filter the desired wavelengths here: set to 0 the undesired spectral components
    filter_mask = (lambdas >= lambda_min) & (lambdas <= lambda_max)
    filtered_spectra = np.multiply(spectra, filter_mask.T)

    # Calculate the XYZ values with the (filtered) spectral information
    filtered_xyz = (lx.spectrum.spd_to_xyz(np.vstack([lambdas, filtered_spectra]), relative=True)
                    .reshape(original_shape))
    
    # Do the correct normalization so that OpenCV can understand the XYZ values
    filtered_xyz = (np.nan_to_num(filtered_xyz) * 255 / 100).astype("uint8")
    
    # Convert back to RGB
    filtered_rgb = cv2.cvtColor(filtered_xyz, cv2.COLOR_XYZ2RGB)
    
    return filtered_rgb

original_img = np.array([[[255, 0, 0], [0, 255, 0]],
                         [[0, 0, 255], [255, 255, 0]],
                         [[0, 0, 0], [255, 255, 255]],
                         [[0, 255, 255], [255, 0, 255]]]).swapaxes(0, 1)

# Use 0 and 900 so that no wavelengths are filtered
filtered_img = filter_img(original_img, 0, 900)

f, axes = plt.subplots(1, 2)
axes[0].imshow(original_img , origin='upper')
axes[1].imshow(filtered_img , origin='upper')
```

On the left we can see the original image, and on the right the output (they should be the same as far as I understand):

![imgs](https://user-images.githubusercontent.com/40766662/157249303-94744e65-2d45-4640-aded-76595377730d.png)

Am I doing something wrong? Is the algorithm supposed to work like this?

**Comment by ksmet1977** [comment]
Hi, 
I think it is due to the way you convert xyz to rgb values.

When I use the luxpy xyz to srgb conversion, the filtered image seems ok.
Try the following instead:

`def filter_img(rgb_img, lambda_min, lambda_max):
    # Store the actual shape of the image
    original_shape = rgb_img.shape

    # Calculate the spectrum for each pixel in the image
    spectral_data = tb.convert(rgb_img.reshape(-1, 3), intent="spd")
    lambdas, spectra = spectral_data[0], spectral_data[1:]

    # Filter the desired wavelengths here: set to 0 the undesired spectral components
    filter_mask = (lambdas >= lambda_min) & (lambdas <= lambda_max)
    filtered_spectra = np.multiply(spectra, filter_mask.T)

    # Calculate the XYZ values with the (filtered) spectral information
    filtered_xyz = (lx.spectrum.spd_to_xyz(np.vstack([lambdas, filtered_spectra]), relative=True)
                    .reshape(original_shape))
    
    # Do the correct normalization so that OpenCV can understand the XYZ values
    # filtered_xyz = (np.nan_to_num(filtered_xyz) * 255 / 100).astype("uint8")
    
    filtered_xyz = (np.nan_to_num(filtered_xyz)) # get rid of any nan's
    filtered_rgb = lx.xyz_to_srgb(filtered_xyz).astype('uint8') # convert xyz values to uint8 srgb values
    
    # Convert back to RGB
    # filtered_rgb = cv2.cvtColor(filtered_xyz, cv2.COLOR_XYZ2RGB)
    
    return filtered_rgb`

regards,
Kevin

**Comment by Tenceto** [comment]
Thank you very much! Now it works alright with that example.

However, when I try it on a different image (a real one), the results are still weird to me:

![Messi_img](https://user-images.githubusercontent.com/40766662/157264652-9dfcab40-c983-46a3-b29e-18c5f4486f5b.png)

Is this behaviours supposed to happen?

**Comment by ksmet1977** [comment]
That is because all of your relative Y values in the XYZ array are 100! You have used the rfls as stimulus spectrum. For rgb conversion you need to know the XYZ relative to a perfect white diffuser (Yw=100). So you need to use spd_to_xyz(illuminant, relative=True,rfl = rfls). In addition, the smits_mitsuba or convert function require linearized rgb values (although that wasn't clear from the docstring; I've updated the luxpy code for these functions so that it can be specified whether the input are linearized or not, with linearized input as default to not break older code; available only on github for now). Note that I've used D65 as default illuminant as that is what srgb was designed for. I'm also not sure why you use 'spd' as intent, so I changed that to 'rfl'.
In the code below, I've changed your function as described above and applied it to an example:
```
import numpy as np
import luxpy as lx
import matplotlib.pyplot as plt
import cv2
from luxpy.toolboxes import rgb2spec as tb

def filter_img(rgb_img, lambda_min, lambda_max, ill = lx._CIE_D65):
    # Store the actual shape of the image
    original_shape = rgb_img.shape

    # Calculate the spectrum for each pixel in the image
    spectral_data = tb.convert(rgb_img.reshape(-1, 3), intent="rfl")
    lambdas, spectra = spectral_data[0], spectral_data[1:]

    # Filter the desired wavelengths here: set to 0 the undesired spectral components
    filter_mask = (lambdas >= lambda_min) & (lambdas <= lambda_max)
    filtered_spectra = np.multiply(spectra, filter_mask.T)

    # create temp var for rfls:
    rfls = np.vstack([lambdas, filtered_spectra])
    
    # Calculate the XYZ values with the (filtered) spectral information under a selected illuminant
    filtered_xyz = (lx.spectrum.spd_to_xyz(ill, relative=True, rfl = rfls) # use some illuminant to illuminate the rfls , otherwise the relative xyzs have Y=100 all of them!!
                    .reshape(original_shape))
    
    # Do the correct normalization so that OpenCV can understand the XYZ values
    # filtered_xyz = (np.nan_to_num(filtered_xyz) * 255 / 100).astype("uint8")
    
    filtered_xyz = (np.nan_to_num(filtered_xyz)) # get rid of any nan's
    filtered_rgb = lx.xyz_to_srgb(filtered_xyz).astype('uint8') # convert xyz values to uint8 srgb values
    
    # Convert back to RGB
    # filtered_rgb = cv2.cvtColor(filtered_xyz, cv2.COLOR_XYZ2RGB)
    
    return filtered_rgb

original_img = np.array([[[255, 0, 0], [0, 255, 0]],
                         [[0, 0, 255], [255, 255, 0]],
                         [[0, 0, 0], [255, 255, 255]],
                         [[0, 255, 255], [255, 0, 255]]]).swapaxes(0, 1)

from skimage import data
original_img = data.chelsea()[::5,::5,:]

# rgb_to_spec_smits() and convert() in smits_mistsuba.py require linearized rgb!:
rgb_img_lin = lx.xyz_to_srgb(lx.srgb_to_xyz(original_img),gamma = 1.0, use_linear_part=True)


# Use 0 and 900 so that no wavelengths are filtered
filtered_img = filter_img(rgb_img_lin, 0, 900, ill = lx._CIE_D65)
# filtered_img = filter_img(original_img, 0, 900, ill = lx._CIE_E)


f, axes = plt.subplots(1, 2)
axes[0].imshow(original_img , origin='upper')
axes[1].imshow(filtered_img , origin='upper')
```

**Comment by Tenceto** [comment]
That works perfectly! Thank you so much for your time, I'm just starting to learn about these topics and your comments were super helpful :)
