### ISSUE TITLE
SPD dataset - Light sources database

### ISSUE THREAD

**Issue by hminle** [ksmet1977/luxpy#24]
Hi Kevin,

Thanks for the great library. This is not an issue, but I don't know where to ask it since this repo does not have a discussion forum.
I see in Luxpy we have spectral database, or in some places, I see you are dealing with excel files to get spectral data.
But where can I download those excel files and use it for my research works? 
Is there any good SPD dataset with the corresponding published papers?

Thanks

**Comment by ksmet1977** [comment]
Luxpy has some built-in data, such as CMFs, SPDs, .... Most of these can be found in the data folder (https://github.com/ksmet1977/luxpy/tree/master/luxpy/data). The files extensions are .csv and .dat, I avoid use of excel, so I'm not sure where you have found a load of an excel file in luxpy. Most data comes from CIE, cvrl.org, as well as some other sources (eg several SPDs come from the official TM30 excel calculator released by the IES). 
If you want to download the data you have found in luxpy, why not just save it using python itself? That way you can save it to almost any format you would want.
Hope that answers your question.

**Comment by hminle** [comment]
Thanks, I got it.
