### ISSUE TITLE
Reduce required dependencies?

### ISSUE THREAD

**Issue by swamidass** [ksmet1977/luxpy#25]
I'm looking for a **small** package that can convert from RGB to CAM16UCS (and also Oklab and Srlab2, but they are easy to implement).

- Colorio fits the bill, but it is closed sourced and obfuscated.
- color-science can do conversions, but is a gigantic bloated package.
- colorspacious is nice and light, but it doesn't support Cam16UCS
- luxpy can do the conversions and it is light, but has gigantic bloated dependencies.

Would you be willing to reduce the **required** dependencies?  This would mean removing these dependencies "requires", and ensuring that code still can run without them:

- remove scipy
- remove matplotlib
- remove pandas
- imageio (possibly)

These dependencies could still be part of requirements.txt (for testing and build time), and to support optional functionality. The could also be added to the "extra_requires" section of the package. 

Looking briefly at the code, it appears that none of these dependencies are required for the core logic of luxypy. It is possible that the places they are used could be changed into  lazy imports inside of functions instead of at the top of a file, and this would be enough to make luxpy useful without downloading the larger libraries.

What do you think?

**Comment by ksmet1977** [comment]
I looked into this and even prepared a version with all lazy imports, except for numpy. Problem for now is that I need the interpolation functions from scipy. There is one in numpy, but it can't extrapolate, nor handle uneven intervals. If I find a solution, I might continue with this.

But for now: cam02ucs is not that hard to code, so why don't you try that? (have a look at metrics_fast.py in cri/iestm30/, where I basically programmed a faster xyz_to_cam02ucs function for faster IES TM30 metric calculations).

**Comment by swamidass** [comment]
Thanks for looking at this! Numpy's interpolator can do unevent intervals.

Here is the code. 

```
import numpy as np

# uneven interpolation space
x = (np.linspace(0., 1, 11)) ** 2

# a random function to interpolate by sampling with x
y = x ** 2 + 2 

# the points to interpolate to
x1 = np.linspace(0., 1, 5)

np.interp(x1, x, y)
```

Extrapolation is easy to implement to too, by expanding the x and y vectors on either end with a manually extrapolated point, perhaps maintaining the derivative at each end?

Cam02 isn't really the best. Cam16ucs is much better. You are right that it isn't too hard to implement. And perhaps I will. It's a bit surprising that there isn't already a light way to do this. It's too bad that python doesn't have code shaking yet.
