### ISSUE TITLE
OpenCV now a required dependency

### ISSUE THREAD

**Issue by hohlraum** [ksmet1977/luxpy#3]
I see that `cv2` is now a required dependency in the latest version of luxpy. To date, luxpy has been wonderfully lean, and the dependencies have all been pretty standard for scientific computing users. But OpenCV is something different, it's big, hairy, slow to import, and difficult to install on many architectures.

Any chance that OpenCV could be removed as a requirement, and it's import done locally only in whichever function or module requires it?

I'm happy to provide a PR if this is a direction you're willing to go.

**Comment by ksmet1977** [comment]
I’m  just using it to read, write and show some images. I found that cv2.imshow has problems when called froma jupyter notebook , so I provided the option to use pyplot.imshow (and it’s imread). However, I would also require a way to write the image file. Any suggestions? Scikit-image? Imageio? If there’s anyway to avoid opencv, I would take, it but I don’t want to inadvertently add another difficult to install package to the requirements list.
Thanks.


Van: hohlraum
Verzonden: vrijdag 25 mei 2018 2:38
Aan: ksmet1977/luxpy
CC: Subscribed
Onderwerp: [ksmet1977/luxpy] OpenCV now a required dependency (#3)

I see that cv2 is now a required dependency in the latest version of luxpy. To date, luxpy has been wonderfully lean, and the dependencies have all been pretty standard for scientific computing users. But OpenCV is something different, it's big, hairy, slow to import, and difficult to install on many architectures.
Any chance that OpenCV could be removed as a requirement, and it's import done locally only in whichever function or module requires it?
I'm happy to provide a PR if this is a direction you're willing to go.
