### ISSUE TITLE
detect_peakwl() indexing error when step size is not 1

### ISSUE THREAD

**Issue by cjilum** [ksmet1977/luxpy#33]
Hi Dr. Smet,

When the function "detect_peakwl()" is called with an SPD whose step size is not 1, the "left_ips" and "right_ips" calculated by "signal.peak_widths()" will be Interpolated indexes of the intersections. Since the step size is not 1, adding them to "spd[0,0]" will result in a shift in the reported "mpeaks", or "ValueError(A value ({}) in x_new is above)".

My current workaround is to round up and down "left_ips/right_ips", index the actual wavelength from SPD, and interpolate to identify the intersections.

Regards,
Chenguang

**Comment by ksmet1977** [comment]
Thanks for informing me. Problem should be fixed now.

**Comment by ksmet1977** [comment]
Thanks for informing me. Problem should be fixed now.
