### ISSUE TITLE
Low CCT

### ISSUE THREAD

**Issue by adriahf** [ksmet1977/luxpy#9]
Hello,

I am trying to calculate the circadian-related parameters (CS and CLa, basically) of a given spd and I have noticed that there is an important difference between the luxpy results and the "official" LRC webpage (https://www.lrc.rpi.edu/cscalculator/) results for low CCTs. I suppose that this error is not directly related with the CCT, but the LRC functions have a discontinuity and the circadian sensitivity curve changes at some point (around 3300 K). This behavior can be seen graphically at the webpage of the LRC. I have seen the provided luxpy documentation and there are some comments related with the calculation of these parameters, but I don't know if that issue could be solved in a simple way.

Thank you for creating/maintaining this awesome library.

**Comment by ksmet1977** [comment]
I fixed the error. Should be ok now, but please do an additional independent check. Thanks for letting me know.

regards,
Kevin

**Comment by adriahf** [comment]
Hello Kevin,

I have checked the update and it's working fine. I have tested some CIE illuminants and everything seems correct.

Thank you
